services:
  - type: web
    name: visualflow-studio
    env: python
    plan: free # Demo tier
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: UNSPLASH_SECRET_KEY
        sync: false
      - key: UNSPLASH_REDIRECT_URI
        default: urn:ietf:wg:oauth:2.0:oob
